name: Deploy Azure Event Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-eventhub:
    name: Deploy Azure Event Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Azure CLI
      - name: Authenticate with Azure CLI
        run: az login --use-device-code

      # Step 3: Set Up Terraform
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Import Existing Authorization Rule
      - name: Import Authorization Rule
        run: |
          terraform state list azurerm_eventhub_namespace_authorization_rule.eh_auth_rule || \
          terraform import azurerm_eventhub_namespace_authorization_rule.eh_auth_rule "/subscriptions/1fad5e2e-cd4b-437b-8fff-ee503b4e0e29/resourceGroups/rg-datalake-terraform/providers/Microsoft.EventHub/namespaces/sepsisStreamingEventhubNameSpace/authorizationRules/RootManageSharedAccessKey"

      # Step 6: Plan Terraform Deployment
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Apply Terraform Configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 8: Capture Outputs for Event Hub
      - name: Capture Terraform Outputs
        id: outputs
        run: |
          echo "EVENT_HUB_CONNECTION_STR=$(terraform output -raw eventhub_namespace_connection_string)" >> $GITHUB_ENV
          echo "EVENT_HUB_NAME=$(terraform output eventhub_name)" >> $GITHUB_ENV

      # Step 9: Print Captured Outputs
      - name: Display Outputs
        run: |
          echo "Event Hub Name: ${{ env.EVENT_HUB_NAME }}"
          echo "Sensitive connection string captured successfully."
          echo "To use it securely, refer to the EVENT_HUB_CONNECTION_STR environment variable."

      # Step 10: Use Captured Outputs in Downstream Jobs or Steps
      - name: Use Event Hub Connection String
        run: |
          echo "Using the Event Hub Connection String in a secure way."
          # Example usage of the sensitive connection string
          echo "Event Hub Connection String: ${{ env.EVENT_HUB_CONNECTION_STR }}"
