name: Deploy Azure Event Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-eventhub:
    name: Deploy Azure Event Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Azure CLI
      - name: Authenticate with Azure CLI
        run: az login --use-device-code

      # Step 3: Set Up Terraform
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Plan Terraform Deployment
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Apply Terraform Configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 7: Capture Outputs for Event Hub
      - name: Capture Terraform Outputs
        id: outputs
        run: |
          echo "EVENT_HUB_CONNECTION_STR=$(terraform output -raw eventhub_namespace_connection_string)" >> $GITHUB_ENV
          echo "EVENT_HUB_NAME=$(terraform output -raw eventhub_name)" >> $GITHUB_ENV

      # Step 8: Print Captured Outputs
      - name: Display Outputs
        run: |
          echo "Event Hub Connection String: ${{ env.EVENT_HUB_CONNECTION_STR }}"
          echo "Event Hub Name: ${{ env.EVENT_HUB_NAME }}"
